spring:
  social:
    facebook:
      app-id: 1703067909988571
      app-secret: 9beb77e00676cc7abf5f15df703093f3
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      scope: user_friends,email,public_profile
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me
      userUri: https://graph.facebook.com/me?fields=id,name,picture